<?php

namespace BrauneDigital\MailBundle\Entity;

/**
 * MailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
